/**
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.strata.pricer.capfloor;

import java.io.Serializable;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.strata.data.MarketDataName;
import com.opengamma.strata.data.NamedMarketDataId;

/**
 * An identifier used to access Ibor cap/floor volatilities by name.
 * <p>
 * This is used when there is a need to obtain an instance of {@link IborCapFloorVolatilities}.
 */
@BeanDefinition(builderScope = "private")
public final class IborCapFloorVolatilitiesId
    implements NamedMarketDataId<IborCapFloorVolatilities>, ImmutableBean, Serializable {

  /**
   * The name of the volatilities.
   */
  @PropertyDefinition(validate = "notNull")
  private final IborCapFloorVolatilitiesName name;

  //-------------------------------------------------------------------------
  /**
   * Obtains an identifier used to find Ibor caplet/floorlet volatilities.
   *
   * @param name  the name
   * @return an identifier for the volatilities
   */
  public static IborCapFloorVolatilitiesId of(String name) {
    return new IborCapFloorVolatilitiesId(IborCapFloorVolatilitiesName.of(name));
  }

  /**
   * Obtains an identifier used to find Ibor caplet/floorlet volatilities.
   *
   * @param name  the name
   * @return an identifier for the volatilities
   */
  public static IborCapFloorVolatilitiesId of(IborCapFloorVolatilitiesName name) {
    return new IborCapFloorVolatilitiesId(name);
  }

  //-------------------------------------------------------------------------
  @Override
  public Class<IborCapFloorVolatilities> getMarketDataType() {
    return IborCapFloorVolatilities.class;
  }

  @Override
  public MarketDataName<IborCapFloorVolatilities> getMarketDataName() {
    return name;
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code IborCapFloorVolatilitiesId}.
   * @return the meta-bean, not null
   */
  public static IborCapFloorVolatilitiesId.Meta meta() {
    return IborCapFloorVolatilitiesId.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(IborCapFloorVolatilitiesId.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  private IborCapFloorVolatilitiesId(
      IborCapFloorVolatilitiesName name) {
    JodaBeanUtils.notNull(name, "name");
    this.name = name;
  }

  @Override
  public IborCapFloorVolatilitiesId.Meta metaBean() {
    return IborCapFloorVolatilitiesId.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the name of the volatilities.
   * @return the value of the property, not null
   */
  public IborCapFloorVolatilitiesName getName() {
    return name;
  }

  //-----------------------------------------------------------------------
  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      IborCapFloorVolatilitiesId other = (IborCapFloorVolatilitiesId) obj;
      return JodaBeanUtils.equal(name, other.name);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(name);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(64);
    buf.append("IborCapFloorVolatilitiesId{");
    buf.append("name").append('=').append(JodaBeanUtils.toString(name));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code IborCapFloorVolatilitiesId}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code name} property.
     */
    private final MetaProperty<IborCapFloorVolatilitiesName> name = DirectMetaProperty.ofImmutable(
        this, "name", IborCapFloorVolatilitiesId.class, IborCapFloorVolatilitiesName.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "name");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3373707:  // name
          return name;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends IborCapFloorVolatilitiesId> builder() {
      return new IborCapFloorVolatilitiesId.Builder();
    }

    @Override
    public Class<? extends IborCapFloorVolatilitiesId> beanType() {
      return IborCapFloorVolatilitiesId.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code name} property.
     * @return the meta-property, not null
     */
    public MetaProperty<IborCapFloorVolatilitiesName> name() {
      return name;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 3373707:  // name
          return ((IborCapFloorVolatilitiesId) bean).getName();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code IborCapFloorVolatilitiesId}.
   */
  private static final class Builder extends DirectFieldsBeanBuilder<IborCapFloorVolatilitiesId> {

    private IborCapFloorVolatilitiesName name;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3373707:  // name
          return name;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 3373707:  // name
          this.name = (IborCapFloorVolatilitiesName) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public IborCapFloorVolatilitiesId build() {
      return new IborCapFloorVolatilitiesId(
          name);
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(64);
      buf.append("IborCapFloorVolatilitiesId.Builder{");
      buf.append("name").append('=').append(JodaBeanUtils.toString(name));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
